### ISSUE TITLE
Add setscrew size on page 12 or page 13 of corexy_frame_assembly_instructions.pdf

### ISSUE THREAD

**Issue by bcrazycramer** [machineagency/jubilee#108]
![image](https://user-images.githubusercontent.com/11469506/87095454-9b9b0e80-c1f5-11ea-8aa4-99b0bc13a9c2.png)

![image](https://user-images.githubusercontent.com/11469506/87095474-a6ee3a00-c1f5-11ea-9545-402fdd02667b.png)

**Comment by bcrazycramer** [comment]
I also find it confusing to have the toolchanger_carriage_assembly_instructions_draft.pdf file along with this documentation above. Maybe these can be mixed together?

**Comment by Poofjunior** [comment]
Ahh, ok. The set screw length (8mm) is called out in the toolchanger_carriage_assembly_instructions_draft.pdf file.

These (and all the instructions) are split up to make the work easier to delegate if you're building the machine with help from more than one person. Separate instructions also make good "stopping" points along the way. But I do think that, out of all the instruction sets, that one is the weakest since you don't finish with one part but rather a bunch of miscellaneous parts.

I'm tempted to leave everything as-is for now since that set screw should already be pre-installed by that point. But before that, do you have any other thoughts now knowing about the setup behind the instructions? Do you have any thoughts on how you might've landed here without the setscrew already preinstalled?
