### ISSUE TITLE
47mm parking post has wrong dowel centers

### ISSUE THREAD

**Issue by ljones-adaptive** [machineagency/jubilee#115]
Upon checking the dowel centers for the Pen holder it looks like the 47mm parking post has dowel centers that are to far apart.

I measured the centers of the dowels for the 47mm parking post which are actually 55mm and the centers of the location circles for the passive pen holder which is 47mm.

So, at some time it looks like the 47mm tool holder got stretched to 55mm dowel centers.

**Comment by Poofjunior** [comment]
Yeah; I thought I fixed this a while ago. It turns out I was driving the model with the wrong parameter.

The revision number is ticked (so we don't confuse these parts) and the number is now fixed.
* the XX values in PPBXX-04 and THXX-04 should now reflect the center to center dowel pin distance.
* PPB47-04 and TH47-04 re-exported
* PP55 is now created, which is the corrected default tool parking post
*  instructions for the tool holder are now updated
* wiki is up to date with links
