### ISSUE TITLE
Thermal Fuses housing may be electrically conductive. AC Shock hazard.

### ISSUE THREAD

**Issue by HaythamB** [machineagency/jubilee#172]
Some variants of TCO fuses come with a metal body, which is conductive for the full AC current loading of the silicone mat they're mated to. This can be an electrical hazard to users, and should be highlighted in the installation notes/warnings to avoid anyone getting a nasty jolt if they're tempted to touch the fuse while in operation.

Its essentially an exposed AC mains terminal, and needs to be treated accordingly.

**Comment by Poofjunior** [comment]
ok, for the one spec'ed as optional in the wiring diagram, it's some sort of electrically insulating material (7MegaOhms according to my multimeter.) I think we're in the clear since it's not only high resistance; it's also meant to be clamped such that it's touching the silicone pad, not the metal plate.
